[package]
name = "axutils-scheduler-feature-matrix"
version = "0.0.0"
edition = "2021"
publish = false

[features]
default = []
none = []
chrono = ["axutils/chrono"]
chrono-tz = ["axutils/chrono_tz"]
tokio = ["axutils/tokio"]
croner = ["axutils/croner"]
chrono-chrono-tz = ["axutils/chrono", "axutils/chrono_tz"]
chrono-tokio = ["axutils/chrono", "axutils/tokio"]
chrono-croner = ["axutils/chrono", "axutils/croner"]
chrono-tz-tokio = ["axutils/chrono_tz", "axutils/tokio"]
chrono-tz-croner = ["axutils/chrono_tz", "axutils/croner"]
tokio-croner = ["axutils/tokio", "axutils/croner"]
chrono-chrono-tz-tokio = ["axutils/chrono", "axutils/chrono_tz", "axutils/tokio"]
chrono-chrono-tz-croner = ["axutils/chrono", "axutils/chrono_tz", "axutils/croner"]
chrono-tokio-croner = ["axutils/chrono", "axutils/tokio", "axutils/croner"]
chrono-tz-tokio-croner = ["axutils/chrono_tz", "axutils/tokio", "axutils/croner"]
all = ["axutils/chrono", "axutils/chrono_tz", "axutils/tokio", "axutils/croner"]
negative-root-module-alias = [
    "axutils/chrono",
    "axutils/chrono_tz",
    "axutils/tokio",
    "axutils/croner",
]

[dependencies]
axutils = { path = "../../..", default-features = false }
